spaces = ' '*25
print('%s 12 Butts Wynd' % spaces)
print('%s Twinklebottm Heath' % spaces)
print('%s West Snoring' % spaces)
print()
print()
print('Dear Sir')
print()
print('I wish to report that tiles are missing from the')
print('outside toilet roof.')
print('I thinki it was bad wind the other night that blew them away.')
print()
print('Regards')
print('Malcome Dithering')

print(1000* 'snirt')